apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ilonkasie-poi-gateway-app-dev
  annotations:
    argocd/app-name: ilonkasie-poi-gateway-app-dev
    backstage.io/kubernetes-id: ilonkasie-poi-gateway-app
    backstage.io/kubernetes-namespace: ilonkasie
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/ilonkasie-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/ilonkasie/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/ilonkasie/deployments/ilonkasie-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/ilonkasie-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ilonkasie"
  system: workshop-system-ilonkasie
  providesApis:
    - gateway-api-ilonkasie
  consumesApis:
    - backend-api-ilonkasie
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ilonkasie
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ilonkasie"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-ilonkasie
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://ilonkasie-poi-gateway-app-ilonkasie.apps.rosa-m9x67.dusy.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-lab/ilonkasie-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/ilonkasie"
  system: workshop-system-ilonkasie
  definition:
    $text: https://github.com/rhdh23-lab/ilonkasie-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
